.PHONY: all clean

PLATFORM = PLATFORM_WEB
BUILD_MODE ?= RELEASE

THIS_DIR=$(shell pwd)
BIN_DIR=$(THIS_DIR)/bin
SRC_DIR=$(THIS_DIR)/src
DEPS_DIR=$(THIS_DIR)/deps
INCLUDE_DIR=$(THIS_DIR)/include
BUILD_DIR = $(THIS_DIR)/build/$(PLATFORM)
LIB_DIR = $(THIS_DIR)/lib/$(PLATFORM)

PROJ_SRCS = $(shell find $(SRC_DIR) -type f -name '*.c')
BIN_NAMES = golova

# ------------------------------------------------------------------------
# Define compiler: CC
CC = emcc
LDFLAGS =
CFLAGS =

# ------------------------------------------------------------------------
# Define compiler flags: CFLAGS
CFLAGS += -Wall -std=c99 -D_DEFAULT_SOURCE -Wno-missing-braces

ifeq ($(BUILD_MODE),DEBUG)
	CFLAGS += -s ASSERTIONS=1 --profiling
else
	CFLAGS += -Os
endif

# ------------------------------------------------------------------------
# Define library paths containing required libs: LDFLAGS
LDFLAGS += \
	-L$(LIB_DIR) \
	-lm -lpthread -ldl -lGL -lstdc++ \
	--shell-file $(RAYLIB_SRC_DIR)/minshell.html \
	-s WASM=1 -s MAX_WEBGL_VERSION=2 -s MIN_WEBGL_VERSION=2 -s USE_GLFW=3 -s FORCE_FILESYSTEM=1 \
	--preload-file ./resources \
	$(LIB_DIR)/libraylib.a


# ------------------------------------------------------------------------
# Define include paths for required headers: INCLUDE_PATHS
INCLUDE_PATHS = -I$(INCLUDE_DIR)

# ------------------------------------------------------------------------
# Raylib
RAYLIB_VERSION=5.0
RAYLIB_URL=https://github.com/raysan5/raylib/archive/refs/tags/$(RAYLIB_VERSION).tar.gz
RAYLIB_NAME=raylib-$(RAYLIB_VERSION)
RAYLIB_DIR=$(DEPS_DIR)/$(RAYLIB_NAME)
RAYLIB_ARCHIVE_PATH=$(DEPS_DIR)/$(RAYLIB_NAME).tar.gz
RAYLIB_SRC_DIR=$(RAYLIB_DIR)/src

# ------------------------------------------------------------------------
# Project
golova: bin/golova.c
	$(CC) -o $(BUILD_DIR)/$@.html $< $(CFLAGS) $(INCLUDE_PATHS) $(LDFLAGS) -D$(PLATFORM) $(PROJ_SRCS) \
	-s MAXIMUM_MEMORY=1gb \
	-s ALLOW_MEMORY_GROWTH=1 \
	-s STACK_SIZE=100MB \
	-s TOTAL_MEMORY=256MB \
	--preload-file resources

# ------------------------------------------------------------------------
# Dependencies
create_dirs:
	mkdir -p $(DEPS_DIR) $(INCLUDE_DIR) $(LIB_DIR) $(BUILD_DIR);

download_raylib:
	if [ ! -d $(RAYLIB_DIR) ]; then \
		wget $(RAYLIB_URL) -O $(RAYLIB_ARCHIVE_PATH); \
		tar zxvf $(RAYLIB_ARCHIVE_PATH) -C $(DEPS_DIR); \
	fi

install_raylib:
	cd $(RAYLIB_SRC_DIR) \
	&& make PLATFORM=$(PLATFORM) \
	&& sudo make install \
		RAYLIB_INSTALL_PATH=$(LIB_DIR) \
		RAYLIB_H_INSTALL_PATH=$(INCLUDE_DIR) \
	&& cp --update $(RAYLIB_SRC_DIR)/rcamera.h $(INCLUDE_DIR);

deps: \
	create_dirs \
	download_raylib \
	install_raylib
	rm -f $(DEPS_DIR)/*.tar.gz;

